name: rust-tests

on: workflow_dispatch

jobs:
  working:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust_tests/working
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./
        with:
          command: check
          toolchain: stable
          args: --all-targets --all-features

  not-working:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust_tests/working
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./
        with:
          command: build
      - uses: ./
        with:
          command: build
          args: --all-features

  cross:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: working
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - uses: ./
        with:
          command: build
          args: --target aarch64-unknown-linux-gnu
          use-cross: true
